# Garotinhas

## Medidas Antropométricas

O crescimento individual das crianças pode ter uma grande variação.

Várias medidas de crescimento colocadas como pontos no gráfico ao longo do tempo e unidas entre si formam uma linha. Essa linha representa o crescimento da criança, ou seja, sua curva de crescimento, que sinaliza se a criança está crescendo adequadamente ou não.

In [1]:
import plotly.io as pio
from datetime import date
from data_processing import *

pio.renderers.default = "notebook_connected"

### Peso para a idade

In [2]:
plot_df(source['wfa_z'], description = 'Peso', months_to_plot=months_to_plot)

### Perímetro cefálico para a idade

In [3]:
plot_df(source['hcfa_z'], description = 'Perímetro Cefálico', months_to_plot=months_to_plot)

### Estatura para a idade

In [4]:
plot_df(source['lfa_birth_z'], description = 'Estatura', months_to_plot=months_to_plot)

## Registros

### Maria

In [5]:
maria

             Peso  Estatura  Perímetro Cefálico     Months
2025-05-29  10.00      89.0                46.0  31.406045
2024-11-13   9.31      84.0                45.5  24.934297
2024-07-24   8.61      80.0                44.5  21.254928
2024-05-15   8.53      77.5                44.4  18.955322
2024-02-06   8.29      74.5                44.0  15.703022
2023-12-13   7.84      72.5                43.0  13.896189
2023-11-03   7.64      71.0                42.8  12.582129
2023-09-21   7.28      68.8                42.3  11.169514
2023-08-24   6.96      67.8                42.0  10.249671
2023-07-23   6.75      66.0                41.5   9.198423
2023-06-12   6.33      64.0                40.8   7.851511
2023-05-11   5.78      62.7                40.3   6.800263
2023-03-17   5.25      59.5                39.0   4.993430
2023-02-13   4.85      58.0                38.0   3.942181
2023-01-16   4.30      54.0                37.5   3.022339
2022-12-19   3.75      51.0                37.0   2.102497
2022-11-14   2.84      48.5                35.5   0.952694
2022-10-24   2.17      44.5                31.5   0.262812
2022-10-19   2.10      44.0                31.5   0.098555
2022-10-16   2.23      44.0                31.5   0.000000

### Sofia

In [6]:
sofia

              Peso  Estatura  Perímetro Cefálico     Months
2025-05-29  11.600      91.0                47.2  31.406045
2024-11-13  10.590      85.0                48.0  24.934297
2024-07-24   9.970      82.0                47.5  21.254928
2024-05-15   9.510      80.5                46.5  18.955322
2024-02-06   8.830      76.0                46.0  15.703022
2023-12-13   8.340      74.0                45.0  13.896189
2023-11-03   8.190      73.0                44.0  12.582129
2023-09-21   7.650      71.5                44.0  11.169514
2023-08-24   7.440      69.8                43.3  10.249671
2023-07-27   7.159      69.2                43.0   9.329829
2023-06-12   6.740      67.0                42.0   7.851511
2023-05-11   6.300      66.5                41.8   6.800263
2023-03-17   5.670      62.5                40.5   4.993430
2023-02-13   5.270      60.0                39.6   3.942181
2023-01-16   4.880      57.0                38.5   3.022339
2022-12-19   4.110      55.0                37.0   2.102497
2022-11-14   3.100      50.7                35.0   0.952694
2022-10-24   2.310      45.0                32.5   0.262812
2022-10-19   2.145      44.5                32.5   0.098555
2022-10-16   2.310      44.5                32.5   0.000000